ktor {
    deployment {
        host = "0.0.0.0"
        port = 3000
        rootPath = "/api/v1"
    }
}

jwt {
    secret = ${?JWT_SECRET}
}

llm {
    hfSecret = ${?HF_SECRET}
    hfModel = "Qwen/Qwen2.5-7B-Instruct:together"
    temperature = 0.0
    maxTokens = 300
}