name: Build

on:
  workflow_call:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Give permission to gradle wrapper
        run: chmod +x ./gradlew
      - name: Run setup script
        run: |
          sudo chmod 777 ./setup_env.sh
          ./setup_env.sh
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Docker compose up
        run: |
          sed -i "s/^HF_SECRET=.*/HF_SECRET=${{ secrets.HF_SECRET }}/" ./jvmapp/.env
          docker compose up --build -d --wait
      - name: Gradle test
        run: ./gradlew clean test

  success:
    needs:
      - build-and-test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Verify there are no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
